name: learn-github-actions
on:
  push:
    branches:
      - master
jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm ci
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build --configuration production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: ./docs
          destination_dir: ./docs
          publish_branch: master
